---
title: "Investigation_of_coefficient_correlation_with_data"
author: "Junting Ren"
date: "2/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("../functions/simulate_genetic_data.r")
source("../functions/plot_cs.R")
source("../functions/SCB_to_CS.R")
library(tidyverse)
```

```{r}
n = 1000
sd_error = 2
beta_num = 50
beta = rnorm(beta_num)
# Correlation matrix for the X
cor = ar1_cor(beta_num - 1,0)
covariance = var* cor
X = cbind(rep(1,n), MASS::mvrnorm(n = n, mu = rep(0,dim(covariance)[1]),Sigma = covariance))
y = X %*% beta +rnorm(n, sd = sd_error)
df_fit = data.frame(y= y, X[,-1])
cov_matrix = vcov(lm(y~., df_fit))
cor_matrix = cov2cor(cov_matrix)
diag(cor_matrix)=NA
hist(abs(cor_matrix))
mean(abs(cor_matrix), na.rm = T)
```

```{r}
beta = c(2,1,0.5,-1.2, -0.5, 1.8, 1.1)
X = cbind(x0 = rep(1,n), x1 = rnorm(n), x2 =  rnorm(n))
y =  X[,1]*beta[1] + X[,2]*beta[2]+(X[,2]^2)*beta[3] +(X[,2]^3)*beta[4] +
  (X[,3])*beta[5] +  (X[,3]^2)*beta[6] +  (X[,3]^3)*beta[7]+ rnorm(n, sd=sd_error)
data_fit = data.frame(y, dplyr::select(data.frame(X), x1, x2))
model = "y ~ poly(x1,3)+poly(x2,3)"
cov_matrix = vcov(lm(as.formula(model), data_fit))
cor_matrix = cov2cor(cov_matrix)
diag(cor_matrix)=NA
hist(abs(cor_matrix))
mean(abs(cor_matrix), na.rm = T)
```


```{r}
n = 1000
sd_error = 2
beta_num = 3         
beta = rnorm(beta_num)
# Correlation matrix for the X
cor = ar1_cor(beta_num - 1,0)
covariance = var* cor
X = cbind(rep(1,n), MASS::mvrnorm(n = n, mu = rep(0,dim(covariance)[1]),Sigma = covariance))
y = X %*% beta +rnorm(n, sd = sd_error)
df_fit = data.frame(y= y, X[,-1])
cov_matrix = vcov(lm(y~., df_fit))
cor_matrix = cov2cor(cov_matrix)
diag(cor_matrix)=NA
hist(abs(cor_matrix))
mean(abs(cor_matrix), na.rm = T)


x1 =  seq(-1,1,length.out = 100)
x2 = seq(-1,1,length.out = 100)
grid_df = data.frame( expand.grid(x1 = x1, x2 =  x2) )# dataset for model fit inside the function
pred_data =as.matrix(cbind(x0 = rep(1,100*100), expand.grid(x1 = x1, x2 =  x2) )) # for producing the
X_design = model.matrix(formula(~ x1+x2, data = data.frame(pred_data)))
cov_pred = X_design %*% cov_matrix %*% t(X_design)
cor_pred = cov2cor(cov_pred)
diag(cor_pred) = NA
mean(cor_pred, na.rm = T)
```

